d | commands |  | 3 items |  | Claude Paroz | claude@2xlibre.net | 1335725835 |  | Fixed #18013 -- Use the new 'as' syntax for exceptions.  Thanks Clueless for the initial patch. Note that unittest has been purposely left out (external package only used by Python 2.6).
f | __init__.py | s | 0B | 0 | Justin Bronn | jbronn@gmail.com | 1217959986 |  | Merged the gis branch into trunk.   git-svn-id: http://code.djangoproject.com/svn/django/trunk@8219 bcc190cf-cafb-0310-a4f2-bffc1f526a37
